baseurl = "https://clmbmb.github.io/dealenoastre"
title = "de-ale noastre, românești"
author = "buplic"
canonifyurls = true
languagecode = "ro"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "de-ale noastre"
  disableWebFonts = false

[[menu.main]]
    name = "Despre"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Mastodon"
    url  = "https://fosstodon.org"
